INSERT INTO FILMS (FILM_NAME,FILM_DESCRIPTION,FILM_RELEASE_DATE, FILM_DURATION, FILM_MPA)
VALUES ( 'testName', 'testDescription', '100L', '2000-01-01', '1');
INSERT INTO FILMS (FILM_NAME,FILM_DESCRIPTION,FILM_RELEASE_DATE, FILM_DURATION, FILM_MPA)
VALUES ( 'testName1', 'testDescription1', '101L', '2001-01-01', '1');
INSERT INTO FILMS (FILM_NAME,FILM_DESCRIPTION,FILM_RELEASE_DATE, FILM_DURATION, FILM_MPA)
VALUES ( 'testName2', 'testDescription2', '102L', '2002-01-01', '1');
INSERT INTO USERS (USER_NAME, USER_EMAIL, USER_LOGIN, USER_BIRTHDAY)
VALUES ( 'testName', 'test@test.com', 'testLogin', '2000-01-01');
INSERT INTO USERS (USER_NAME, USER_EMAIL, USER_LOGIN, USER_BIRTHDAY)
VALUES ( 'testName1', 'test1@test.com', 'test1ogin1', '2001-01-01');
INSERT INTO USERS (USER_NAME, USER_EMAIL, USER_LOGIN, USER_BIRTHDAY)
VALUES ( 'testName2', 'test2@test.com', 'testLogin2', '2002-01-01');